{% set name = "pysheds" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 554b31e8ba2206f2a45d99c3982861b563e1528c3d1c3e4f63de7f3271d4ce5e

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numba
    - numpy
    - pandas
    - scipy
    - pyproj
    - scikit-image
    - affine
    - geojson
    - rasterio >=1

test:
  imports:
    - pysheds
    - pysheds.grid
    - pysheds.view
    - pysheds.io

about:
  home: http://github.com/mdbartos/pysheds
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - mdbartos
