{% set name = "pysheds" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5885b9f8dd2d18e237df53a0fd0edec9c9e9a46ed58ae8b16c0f0ae2d332fcbe

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numba
    - numpy
    - pandas
    - scipy
    - pyproj
    - scikit-image
    - affine
    - geojson
    - rasterio >=1

test:
  imports:
    - pysheds
    - pysheds.grid
    - pysheds.view
    - pysheds.io

about:
  home: http://github.com/mdbartos/pysheds
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - mdbartos
