travis:
  secure:
    BINSTAR_TOKEN: pImmvtTP86U29fHbOLpdEGpUfHz6qETi8xG5+OlX3AO8bxq3NxVZiCPRECPrz5oT7UF8rydcSmJuy4rkSmfqiJSM5gWoonVh7dMeKWtDk3Tw5RRAYq7gmteLNmYzm1rODtE6dQrZiVmXA6m7IAz7xcLrqyBTriUUXU7nfqxdVQZ9ROGQMxsxf93YbzO+4Lr5jgigoveUrlJIXiwANrWwImmNKLyX/KEKW+HVfwBrYy/Ol8C6HIfo7W2KuyG/WFvkO1jdBn3pRhxaFoa12D+Ep/fUzNnmYGLy8nHjVGTL9asK0dJxWDj/93D3YxCHxm4PgdSvddXEysiGAlGnAr3zKWgF/vOVFi/KpYwdmF2+/OuLJ46vQ66LGYPqFp0j3xhqzd19p7hGRuQwHlKKXlj4aDEebh+CytNg/19l4B44Erf9zIWtrK8l6Xhsm2WmJ95/nrqR/2HPgo3tPaSyKNuHUxUJEJ1j7U0yYPM36+4tX+QZ4bUixoLjhuDDL9RT9MZND+9S1ct/EDRG7FyIhIi74FzcDLxWCNlcEwA9rF2Qxr95sLK930rRcHk8q4cNrZSWmI0eqpMnQv0JCJOAoNeRCeKdtUmEgjLeA1OAHd4nRhfX1U7ScdZ67hr3eq6ojOAiomjVCow4S7VqMHoUf3jetjBYsqPCZGFiyJuVvg6Jv4g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
