travis:
  secure:
    BINSTAR_TOKEN: RwpRl6oDJx1Yvdr65TFoFwl2E4QstSOJvPNq3hW/y/YAByGW28Fyr53n8gUwk23D8/XsfGNDy42FfiQr+FBfuQtRwkX0VUz3XIiqvmotK6ubvAXwOT9pbbGlQ2iagzxtQ/kpWuuoIXRo9jkicIQZTR2k/WNFsQ9QnDFEKgxuR7Uo/EqeWB42Qn5BoLJgoVompAHLeR61Fpx5RtLMOflj8lCLbQgsePG53VbfCly0gt7fAdyrlXF/ToKhqzr1MrMrFqAml7acmQpuC1yWmJXF/EezkuDSEHInKXRbd3751aIX+Js7J5VwPMn4jFkAcq60lC/BeVUvWXQWjyYpeSlm3X3j/wSs6hlc6QMRfiUTBS7Ynq4QroayUpC52hrBLolqCfdWZidC3e4aZncKlYE/DWe7DMgVbQZYbuGwnJFtD/wJ6CMtoghxyjskPeC6FmK0G51vNV64f1KbvtEynNpNGQWY2nSTqSY9LDFj1JBjDvaljYvxCbYTxgpQecu2un4RYcxfrSew4bi0m+2+xe1ULsfEV4H6aRngOTcXwq3iztZoJUWMvx9zCBFpJMVVRT1r9iGFIQWfJ+Rm6CUZU1gotdPMfyp7flkn3bkodEm/vA7R6hutJdPmh2vTPce/lk+Xh6UdjP+xW3ttBG6EWTiG1zI9/UIsAHF9nOzJE/1+Ups=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
